#### NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
# slicing(same like python)
# [start, stop, step]
arr[0:5:2]

array([0, 2, 4])

In [4]:
# Note: if we get any portion of an array & change the those values it will effect the main array also

slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [5]:
slice_of_arr[:] = 1
slice_of_arr

array([1, 1, 1, 1, 1, 1])

In [6]:
arr

array([ 1,  1,  1,  1,  1,  1,  6,  7,  8,  9, 10])

In [7]:
# copy an array
arr_copy =  arr.copy()
arr_copy

array([ 1,  1,  1,  1,  1,  1,  6,  7,  8,  9, 10])

In [8]:
# two dimensional array
arr_2d =  np.array([[5,10,15], [20,25,30],[35,40,45]])

In [9]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
# get value(40)
# double bracket notation -> [row][column] 
arr_2d[2][1]

40

In [11]:
# single bracket notation -> [row, column] 
arr_2d[2,1]

40

In [12]:
# grava subsection
arr_2d[:2, :2]

array([[ 5, 10],
       [20, 25]])

###### conditional statement

In [13]:
arr = np.arange(1,11)

In [14]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [15]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [16]:
# short form
arr[arr > 5]

array([ 6,  7,  8,  9, 10])