### NumPy Arrays

In [1]:
import numpy as np

In [2]:
# one dimensional(vector) from list
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
# two dimensional(matrix) from list of list
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### arange

In [4]:
# np.arange([start,] stop[, step,], dtype=None)
# stop
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# start, stop
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [6]:
# start, stop, step
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

###### zeros

In [7]:
# np.zeros(shape, dtype=float, order='C')
# one dimensional 
np.zeros(3)

array([0., 0., 0.])

In [8]:
# two dimensional 
# (rows,columns) -> (2,3)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

###### ones

In [9]:
# np.ones(shape, dtype=None, order='C')
# one dimensional 
np.ones(3)

array([1., 1., 1.])

In [10]:
# two dimensional
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

###### linspace

In [11]:
# Return evenly spaced numbers over a specified interval.

# np.linspace(
#     start,
#     stop,
#     num=50,
#     endpoint=True,
#     retstep=False,
#     dtype=None,
#     axis=0,
# )

np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

###### identity matrix

In [12]:
# np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###### random

In [13]:
# one dimension 
np.random.rand(5)

array([0.81983384, 0.93606926, 0.92669441, 0.76456386, 0.39823876])

In [14]:
# two dimension
np.random.rand(2,3)

array([[0.27709866, 0.7812925 , 0.05551594],
       [0.5111377 , 0.24041292, 0.8109061 ]])

In [15]:
# normal numbers
np.random.randn(2,3)

array([[ 1.9534955 ,  0.64368282, -0.40579596],
       [-0.4279333 , -0.16557792, -0.83138085]])

In [16]:
# randint(low, high=None, size=None, dtype='l')
# single
np.random.randint(5, 10)

6

In [17]:
# array of given size
np.random.randint(1, 10, 5)

array([5, 1, 3, 1, 6])

###### min, max, shape, reshape, dtype

In [18]:
ranarr = np.random.randint(1, 100, 10)

In [19]:
# max value
ranarr.max()

89

In [20]:
# index location of the max value
ranarr.argmax()

7

In [21]:
# min value
ranarr.min()

15

In [22]:
# index location of the min value
ranarr.argmin()

2

In [23]:
# reshape
arr = np.arange(0, 10)
# [0 1 2 3 4 5 6 7 8 9]
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# get shape
arr.shape

(10,)

In [25]:
# get data type
arr.dtype

dtype('int32')